---
# tasks file for roles/webservers
- name: Copy application file
  copy:
    src: ../files/index.php
    dest: "{{path_to_app}}"
    mode: 0755

- name: Create simple info page
  copy:
    dest: "{{path_to_app}}/info.php"
    content: "<h1>{{ansible_hostname}}</h1>"

- name: See dir contents
  command: ls -la {{path_to_app}}
  register: dir_contents

- name: Debug dir contents
  debug:
    msg: "{{dir_contents}}"
    
- name: Configure php.ini file
  lineinfile:
    path: /etc/php.ini
    regex: ^short_open_tag
    line: 'short_open_tag=On'
  notify: restart apache