# Setup the app
---
  - hosts: webservers
    become: true
    vars:
      path_to_app: "/var/www/html"
    # vars_files:
    #   - ../vars/secret-varibles.yaml
    vars_prompt:
      - name: "upload_var"
        prompt: "Copy over the index.php file?"
      - name: "create_var"
        prompt: "Create info.php page?"
    tasks:
      # - name: use secret pwd here
      #   debug:
      #     msg: "{{secret_password}}"
      #   tags: debug
      - name: Copy application file
        copy:
          src: ../index.php
          dest: "{{path_to_app}}"
          mode: 0755
        when: upload_var == 'yes'
        tags: copy
      - name: Create simple info page
        copy:
          dest: "{{path_to_app}}/info.php"
          content: "<h1>{{ansible_hostname}}. These are changes.</h1>"
        when: create_var == 'yes'
        tags: create
      - name: See dir contents
        command: ls -la {{path_to_app}}
        register: dir_contents
      - name: Debug dir contents
        debug:
          msg: "{{dir_contents}}"
      - name: Configure php.ini file
        lineinfile:
          path: /etc/php.ini
          regex: ^short_open_tag
          line: 'short_open_tag=On'
        notify: restart apache
    handlers:    
      - name: restart apache
        service: name=httpd state=restarted